name: RELEASE APP

inputs:
  tag:
    description: "Release tag (e.g., v0.1.0)"
    required: true
  homebrew_tap_token:
    description: "PAT for homebrew-tap repository"
    required: true
  tauri_signing_private_key:
    description: "Tauri updater signing private key"
    required: true
  tauri_signing_private_key_password:
    description: "Tauri updater signing private key password"
    required: false
    default: ""
  apple_certificate:
    description: "Apple Developer ID certificate (base64)"
    required: true
  apple_certificate_password:
    description: "Apple certificate password"
    required: true
  apple_signing_identity:
    description: "Apple signing identity"
    required: true
  apple_id:
    description: "Apple ID for notarization"
    required: true
  apple_password:
    description: "Apple app-specific password"
    required: true
  apple_team_id:
    description: "Apple Developer Team ID"
    required: true
  keychain_password:
    description: "CI keychain password"
    required: true

runs:
  using: composite
  steps:
  - name: "Setup Bun"
    uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
  - name: "Setup Rust"
    shell: bash
    run: rustup default stable
  - name: "Install frontend dependencies"
    shell: bash
    run: bun install
  - name: "Import Apple Developer Certificate"
    shell: bash
    env:
      APPLE_CERTIFICATE: ${{ inputs.apple_certificate }}
      APPLE_CERTIFICATE_PASSWORD: ${{ inputs.apple_certificate_password }}
      KEYCHAIN_PASSWORD: ${{ inputs.keychain_password }}
    run: |
      echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
      security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
      security default-keychain -s build.keychain
      security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
      security set-keychain-settings -t 3600 -u build.keychain
      security import certificate.p12 -k build.keychain \
        -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
      security set-key-partition-list -S apple-tool:,apple:,codesign: \
        -s -k "$KEYCHAIN_PASSWORD" build.keychain
      rm certificate.p12
  - name: "Build and release with tauri-action"
    uses: tauri-apps/tauri-action@v0
    env:
      GITHUB_TOKEN: ${{ github.token }}
      TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.tauri_signing_private_key }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.tauri_signing_private_key_password }}
      APPLE_SIGNING_IDENTITY: ${{ inputs.apple_signing_identity }}
      APPLE_ID: ${{ inputs.apple_id }}
      APPLE_PASSWORD: ${{ inputs.apple_password }}
      APPLE_TEAM_ID: ${{ inputs.apple_team_id }}
    with:
      tagName: ${{ inputs.tag }}
      releaseDraft: true
      includeUpdaterJson: true
  - name: "Verify updater assets"
    shell: bash
    env:
      GITHUB_TOKEN: ${{ github.token }}
    run: |
      TAG="${{ inputs.tag }}"
      ASSETS=$(gh release view "${TAG}" --json assets --jq '.assets[].name')
      printf '%s\n' "$ASSETS" | grep -Fxq 'latest.json' || { echo "ERROR: Missing latest.json"; exit 1; }
      printf '%s\n' "$ASSETS" | grep -Eq '\.sig$' || { echo "ERROR: Missing .sig file"; exit 1; }
  - name: "Update Homebrew Cask"
    shell: bash
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GH_PAT: ${{ inputs.homebrew_tap_token }}
    run: |
      TAG="${{ inputs.tag }}"
      VERSION="${TAG#v}"
      DMG_NAME="Agentoast_${VERSION}_aarch64.dmg"

      # Download DMG from release to compute SHA256
      gh release download "${TAG}" --pattern "${DMG_NAME}" --dir /tmp
      SHA256=$(shasum -a 256 "/tmp/${DMG_NAME}" | awk '{print $1}')
      DMG_URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/${DMG_NAME}"

      CASK_CONTENT=$(cat <<CASK_EOF
      cask "agentoast" do
        version "${VERSION}"
        sha256 "${SHA256}"

        url "${DMG_URL}"
        name "Agentoast"
        desc "macOS menu bar notification app for AI coding agents"
        homepage "https://github.com/${{ github.repository }}"

        auto_updates true
        app "Agentoast.app"

        zap trash: [
          "~/.local/share/agentoast",
          "~/.config/agentoast",
        ]
      end
      CASK_EOF
      )

      ENCODED=$(echo "${CASK_CONTENT}" | base64)
      EXISTING_SHA=$(GH_TOKEN="${GH_PAT}" gh api repos/shuntaka9576/homebrew-tap/contents/Casks/agentoast.rb --jq '.sha' 2>/dev/null || echo "")

      if [ -n "${EXISTING_SHA}" ]; then
        GH_TOKEN="${GH_PAT}" gh api repos/shuntaka9576/homebrew-tap/contents/Casks/agentoast.rb \
          --method PUT \
          -f message="Update agentoast cask to ${TAG}" \
          -f content="${ENCODED}" \
          -f sha="${EXISTING_SHA}"
      else
        GH_TOKEN="${GH_PAT}" gh api repos/shuntaka9576/homebrew-tap/contents/Casks/agentoast.rb \
          --method PUT \
          -f message="Add agentoast cask ${TAG}" \
          -f content="${ENCODED}"
      fi

      echo "Done! Published ${TAG}"
